### ISSUE TITLE
DWARF errors

### ISSUE THREAD

**Issue by hbent** [arnoldrobbins/struct#1]
I'm getting odd DWARF errors when trying to compile the modernize branch on Gentoo Linux.  This is with gcc 11.2.1:

cc -g -g3 -m32 beauty.o tree.o lextab.o bdef.o -o beautify
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: tree.o:/usr/local/src/struct/src/b.h:11: multiple definition of `xxt'; beauty.o:/usr/local/src/struct/src/b.h:11: first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: lextab.o:/usr/local/src/struct/src/b.h:11: multiple definition of `xxt'; beauty.o:/usr/local/src/struct/src/b.h:11: first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: DWARF error: section .debug_str is larger than its filesize! (0x294b vs 0x25d8)
bdef.o:/usr/local/src/struct/src/bdef.c:5: multiple definition of `xxt'; beauty.o:/usr/local/src/struct/src/b.h:11: first defined here
collect2: error: ld returned 1 exit status

That DWARF error is not something that I've seen before, and I'm not at all clear why it would be happening.  When switching to clang I do not see these errors, though I do still see the multiple definition of "xxt" (which is obviously a different issue).

**Comment by arnoldrobbins** [comment]
Thanks for the report. I just fixed the multiple definition of `xxt`.  Please pull

As for the DWARF errors, I suggest removing the `-g -g3` flags from the makefile, then it will probably compile.  I've been using the standard GCC on Ubuntu 18 and 20, they aren't as current as GCC 11.

Hmm, I have GCC 11.2 installed and it works ok. This is on Ubuntu 18.04.  So, I don't know what to tell you.

**Comment by hbent** [comment]
Sure, disabling debugging works just fine, and in fact it's just the `-g3` that's causing issues; regular `-g` is fine.  I just wanted to report it to see if it was exposing some sort of underlying issue.

I did a pull but am still seeing a multiple definition issue between bdef.c and beauty.y.

**Comment by arnoldrobbins** [comment]
OK. Just fixed the multiple definition issue. Thanks. Don't know what  to tell you about `-g3` other than "it works for me"...

**Comment by hbent** [comment]
OK, it's obviously not a big deal, I'll go ahead and close this.  Thanks!
